repo: https://github.com/elba-docker/experiment.git
experiments_path: experiments
username: jazevedo
options:
  USERNAME: jazevedo
tests:
    # Experiment to test the performance of rAdvisor during load interference
  - id: li
    replicas: 1
    experiment: load_interference
    profile: MicroblogBareMetalD430
    branch: feature/load-interference
    options:
      HOSTS_TYPE: physical
      HARDWARE_TYPE: d430
      # Experiment parameters
      T_RAMP: 20
      T_BUFFER: 10
      T_COLLECTION: 200
      CPU_PER_STRESS_CONTAINER: 1.0
      NUMBER_SESSIONS: 135
      RADVISOR_NICENESS: -1
      COLLECTL_NICENESS: -1
      ENABLE_COLLECTL: 1
      ENABLE_RADVISOR: 1
      WISE_DEBUG: 1
    matrix:
      - name: enable_load
        values:
          - id: l
            options:
              ENABLE_LOAD_INTERFERENCE: 1
          - id: nl
            options:
              ENABLE_LOAD_INTERFERENCE: 0
